### ISSUE TITLE
how to ignore unknow fields?

### ISSUE THREAD

**Issue by ckelsel** [bk192077/struct_mapping#12]
This is a good library!

While I am having a problem,

``` json
{"code":100000,"message":"success", "encrypt":false}
```

The json may be change in the future, changed may be as follows

``` json
{"code":100000,"message":"success", "encrypt":false, "test":0}
```

the program will crash after receive new json data,

how can I ignore `test` field?

**Comment by bk192077** [comment]
It is not right.
I changed this behavior (new commit to master). Now the unknown field in json does not throw an exception.

**Comment by ckelsel** [comment]
good job.
