### ISSUE TITLE
Omnet ++

### ISSUE THREAD

**Issue by OverwatchGirl** [bk192077/struct_mapping#4]
Hello ! i tried using the library in a project on omnet++ , and it shows that it doesn't recognize some functions used in the library as well as some ")" missing . i am using c++ 17 and  gcc, g++ version 10.2

**Comment by bk192077** [comment]
Hello!
If you give me an example project, I will try to see why this is happening.

**Comment by OverwatchGirl** [comment]
Hello again !

I actually tried to run one of your examples in omnet++ i didn't add nothing, just created an omnet++ project, then i created a .cpp file, where i pasted the code of your example.

Some of the errors i got : 
- /usr/local/include/struct_mapping/f_map_like.h:41:28: error: 'is_floating_point_v' is not a member of 'std'; did you mean 'is_floating_point'?
   41 |    else if constexpr (std::is_floating_point_v<ValueType<T>>) F_iterate_over::set_floating_point(n, v);

- /usr/local/include/struct_mapping/f_map_like.h:40:55: error: expected primary-expression before ')' token
   40 |    else if constexpr (std::is_integral_v<ValueType<T>>) F_iterate_over::set_integral(n, v);

- /usr/local/include/struct_mapping/f_map_like.h:40:28: error: 'is_integral_v' is not a member of 'std'; did you mean 'is_integral'?
   40 |    else if constexpr (std::is_integral_v<ValueType<T>>) F_iterate_over::set_integral(n, v);
      |                            ^~~~~~~~~~~~~

- /usr/local/include/struct_mapping/f_struct.h:249:23: error: 'is_same_v' is not a member of 'std'; did you mean 'is_same'?
  249 |    if constexpr (std::is_same_v<V, float>) return Member::Type::Float;

Thank you in advance.

**Comment by maggu2810** [comment]
Are you sure you are using std=c++17?
As you can see here
https://en.cppreference.com/w/cpp/types/is_floating_point
`is_floating_point_v` exists since c++17.

**Comment by OverwatchGirl** [comment]
Hey !

yes, i have c++ 17, isn't std=c++17 a part of it ? ! that why these errors seem very weird to , since i guess they are c++ version related

**Comment by bk192077** [comment]
If you just create a project, the same errors appear during compilation. After specifying -std=c++17, everything compiles and runs without errors.

![std](https://user-images.githubusercontent.com/66406226/115775248-511d0400-a3bb-11eb-9db3-0fdadae9f49d.png)

**Comment by OverwatchGirl** [comment]
Weirdly ! i only have "Binary Parsers" and "Error Parsers" under settings !

**Comment by OverwatchGirl** [comment]
Hello ! i just want to inform you that i changed the flag -std=c++17 in the config and makefiles in omnet++ , and it is working now !

Thank you so much @bk192077 and @maggu2810 , i am so grateful for your precious help !
