### ISSUE TITLE
Json file

### ISSUE THREAD

**Issue by OverwatchGirl** [bk192077/struct_mapping#5]
Hello !

I am trying to convert data that i read from a json file into a data structure, but i always get this error : 

_terminate called after throwingan instance of 'struct_mapping::StructMappingException'
  what():  parser: unexpected character 'j' at line 1_

I added "json(" at the beginning of the read data, and ")json" at its end.

**Comment by maggu2810** [comment]
In the examples a raw string literal is used. See (6) of https://en.cppreference.com/w/cpp/language/string_literal

If you read the data from a file, don't at content before and after. You generate an invalid JSON.

**Comment by OverwatchGirl** [comment]
Thank you ! it worked !
